config/routes.rb
Rails.application.routes.draw do	
  get 'books/new'
  post 'books/create'
  get 'books/:id' , to: 'books#show'

  get 'posts/new'
  post 'posts/create'

  get 'posts/:id' , to: 'posts#show'
  get 'posts/:id/edit' ,to: 'posts#edit'
  patch 'posts/:id' , to: 'posts#update'
  delete 'posts/:id' , to: 'posts#destroy'


  resources :students do
  	resources :reviews
  end

  # get 'test1/testoutput'
  get 'test1/testoutput'

  # get 'welcome/index'
  
  resources :articles

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :reviews , dependent: :destroy
	validates :name, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  def create
  @book = Book.new(params.require(:book).permit(:title, :description,:numberofbooks))

  @book.save
   render plain: @book.inspect
  end

   def show
    @book = Book.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params.require(:post).permit(:title, :content))
      render plain: 'success'
    end
  end

  def destroy
  @post = Post.find(params[:id])
  @post.destroy

  render plain: 'Deleted'
end

  def create
    render plain: params[:post].inspect
  	# render text: => "<html><body>Hello</body></html>".html_safe
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

   http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
   
	 def create
    @student = Student.find(params[:student_id])
    @review = @student.reviews.create(review_params)
    redirect_to student_path(@student)
  end

 

  def destroy
    @student = Student.find(params[:student_id])
    @student = @student.reviews.find(params[:id])
    @student.destroy
    redirect_to student_path(@student)
  end

  private
    def review_params
      params.require(:review).permit(:reviewer, :body)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def new
  @student = Student.new
	end

	 http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

 def index
    @student = Student.all
  end

 
def edit
  @student = Student.find(params[:id])
end
 
	
def create
  @student = Student.new(student_params)
 
  if @student.save
  redirect_to @student
   else
    render 'new'
  end
end  

def update
  @student = Student.find(params[:id])
 
  if @student.update(student_params)
    redirect_to @student
  else
    render 'edit'
  end
end

def show
    @student = Student.find(params[:id])
  end
 
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
 
    redirect_to students_path
  end
private
  def student_params
    params.require(:student).permit(:name, :class_name)
  end



end

app/controllers/test1_controller.rb
class Test1Controller < ApplicationController
	 def testoutput
  	render plain: 'test ne dm'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @post = Post.new
    # @post.title = "First post"
    # @post.text = "Sample content"
    # @post.save()
    # render plain: 'Post created!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/test1_helper.rb
module Test1Helper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<%= form_for :article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/new.html.erb
<%= form_for :book, url: '/books/create' do |f| %>
  <p>
    <%= f.label :"Nhap tua de" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :"Nhap tom tat :" %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :"So luong sach :" %><br>
    <%= f.text_area :numberofbooks %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/show.html.erb
<p>
  <h1>Title:</h1>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Number of books:</strong>
  <%= @book.numberofbooks %>
</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for :post, url: '/posts/' + @post.id.to_s, method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/new.html.erb
<%= form_for :post , url: '/posts/create' do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.text %>
</p>


<!--  <p>
  <%= link_to 'destroy', posts_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>  -->

app/views/reviews/_form.html.erb
<%= form_for([@student, @student.reviews.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :reviewer %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<p>
  <strong>Reviewer:</strong>
  <%= review.reviewer %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= review.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [review.student, review],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
 
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :class_name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/students/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing articles</h1>
 
<%= link_to 'New article', new_student_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @student.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.class_name %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Destroy', student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<%= form_for :student, url: students_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :class_name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= form_for :student, url: students_path do |f| %>
  ...
<% end %>
 
<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @student.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @student.class_name %>
</p>


<h2>Reviews</h2>
<%= render @student.reviews %>


<h2>Add a review:</h2>
<%= render 'reviews/form' %>
 
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .title-header {
    color: blue;
    font-family: Lobster , Monospace;
  }

  .small-img{
  	width: 100px;
  }


  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<p>Click here for <a href="#">cat photos</a>.</p>

<h1 class="title-header ">Student Manager Web Application</h1>

<a href="#"><img class="small-img thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt = "cat ihih"></a>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff</p> 

<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>

<form action="/students">
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button> 
</form>

<%= link_to 'Go to app', controller: 'students' %>